global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'portalasig-ms-uaa'
    metrics_path: '/portalasig/uaa/actuator/prometheus'
    static_configs:
      - targets: ['host.gateway:5860']
  - job_name: 'portalasig-ms-site'
    metrics_path: '/portalasig/site/actuator/prometheus'
    static_configs:
      - targets: [ 'host.gateway:5861' ]
  - job_name: 'portalasig-ms-notify'
    metrics_path: '/portalasig/notify/actuator/prometheus'
    static_configs:
      - targets: [ 'host.gateway:5862' ]
